### ISSUE TITLE
No Glide Slope on RNAV Approaches

### ISSUE THREAD

**Issue by RFazio1951** [pimarc/pms50-gns530#13]
I love this 530 patch, and have been practicing approaches with it. Thanks so much.

    I’m guessing this is known, but I figured I’d mention it. The glide slope works so perfect in ILS approaches. In any RNAV approach I have tried, there is no vertical guidance, no indication on the instrument, and no following it by the autopilot. I’ve tried approaches, into my familiar airports, KFOK, and, KISP.

**Comment by pimarc** [comment]
The display of the glideslope is not GPS dependant. This is the HSI of your aircraft.
In the money, for example, there is no glideslope for RNAV.
RNAV approaches work well with the GNS530 including vertical guidance. Just exactly follow the approach sequence, be at the correct altitude at the IAF, and be sure that you have activated the approach and the approach mode on autopilot.
Discussed many times on the forum: https://forums.flightsimulator.com/t/gns530-mod/296598

**Comment by RFazio1951** [comment]
I'm not trying to say there is anything wrong with the GNS530 mod. I
love it and it works well. I've been practicing approaches just for fun. My
plane has a 430 in it and a glass panel, a Dynon, Skyview. It shows the
glideslope, for ILSs and the glidepath on RNAV approaches. How could you do
an RNAV approach without the autopilot with no indication?

       The RNAV 24 approach glidepath definitely does not work to KISP. No
glidepath, no descent on autopilot. Other airports in the area work. This
may be a MSFS problem and not the 530 problem.

       Other things I've noticed:

       If you set up a flight from KISP runway 6 to KFOK runway RNAV 24,
IFR you will see a plan on the map making a big circular path to the north
and into MATTY. Do it in the real 530 and there is a procedure turn at
MATTY. Foreflight shows the same procedure turn. Also could be a MSFS
problem, not the 530? Don't know.

        In the real 530/430 when you get a cursor in direct to, or the
flight plan and want to enter an airport or way point, it always starts on
"K" and you turn the small knob to whatever letter you actually want. in
the GNS530 mod it starts on 0 I think and you have to turn backwards to get
to letters?

        My 430 displays in the message area on the bottom of the screen, a
turn coming up in how many seconds. It counts down the time to the turn and
the turn initiates.

RF

**Comment by pimarc** [comment]
For the RNAV glidescope, I can't do anything. This is not related to the GPS but to the HSI. The instruments are completely independent of each other. The HSI should be able to read the sim's kernel for the RNAV approach information and display it.

I will try the RNAV 24 at KISP and come back to you. Probably a problem with the database. Do you use Navigraph or the standard MSF database?

The story of the circular path is an MSFS issue. The GPS doesn't do anything here. When you start your approach from an opposite direction (ex 180°), the kernel calculates a big circular path. It makes sense but the radius is not dependent on the airplane type and speed. They do the calculation for airliners and not for small airplanes.

Waypoint selection: On the last version of the MOD, the cursor starts with the region letter of your next flight plan active waypoint, so a K in the states. The order of the letters for selection is bad in the MSFS kernel so it starts with the numerics instead of an "A" character. This is a kernel issue. I can't do anything here too.

Message in the bottom area: this is on my to-do list. Not implemented yet.

**Comment by pimarc** [comment]
Tested RNAV 24 at KISP with the Mooney and Navigraph database. Worked very well for me.
I've set the approach mode after CORAM and was at 1400ft at RIZER. The airplane started to descent to the RW24 just after RIZER.
