### ISSUE TITLE
GNS530 Mod not compatible with Carenado PA44 Semiole

### ISSUE THREAD

**Issue by henschroed** [pimarc/pms50-gns530#17]
Have installed the MOD GNS530 with addon linker.
Since then the following displays are without function in the PA44: GNS530, KX165 and KR87. The displays GMA340, KN64 and Garmin transponder work. After I disabled the mod with Addon-Linker all displays work again.
![Avionics Issue](https://user-images.githubusercontent.com/73403563/110714014-214ae000-8203-11eb-8826-9392f39327c7.JPG)

**Comment by pimarc** [comment]
Are you sure you have downloaded the correct package?
This is typically what occurs when you download sources instead of the release.
Please remove the mod from the community folder and install the latest release that you will find here:
https://pms50.com/fs2020/gns530/pms50-gns530.zip

Please install following the instructions in the documentation.
If it persists, try removing all other mods.

The Mod should work with any Carenado aircraft.

**Comment by henschroed** [comment]
Hello pimarc,
many thanks for the quick reply. Have reinstalled the mod from your link. All display work again.
Thank you again and continue please this good work.
Best regards

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10
