### ISSUE TITLE
CTD issue since latest update

### ISSUE THREAD

**Issue by katiepilot** [pimarc/pms50-gns530#18]
Firstly, let me say - what an amazing job you've done with this mod! So thank you!

Since the latest MSFS update, I've updated to the latest version, but it appears to be causing random CTDs... I flew a quick 2hr hop and unfortunately encountered 4 CTDs, then I removed the mod from my community folder and the CTDs stopped.

Sorry you have to deal with these bugs every time Asobo push an update!

**Comment by pimarc** [comment]
Yes, sim's updates are always a challenge for mod providers.
Now the last version is a temporary one made because there were black screens after the sim's update 3.
The new version is nearly ready but I'm waiting for the user's feedback in order to include more fixes if there are some.
Now, if you have CTDs you should try to reproduce them and give me the necessary information as described in the bug reporting chapter in the documentation. You must also try without any other mods installed.

**Comment by katiepilot** [comment]
Thanks, I am not using any other mods. And the crashes happen very sporadically... no real pattern to it. I know that's not much to go on, but it happened 4 times on my system and 1 time on a friend's running the same mod.

We then uninstalled the mod and it rectified it. I will do some more experimenting and see if i can find a precise situation when it crashes in particular...

**Comment by pimarc** [comment]
Hi
There is a new release 1.0.29.
Please try it and let me know. On my side, I didn't get any CTs after some hours of tests.
Be careful to not install the sources instead of the release (see "installation" in the documentation)

**Comment by pimarc** [comment]
Hello. Does it work now?

**Comment by pimarc** [comment]
No feedback from the user so I close the case

**Comment by katiepilot** [comment]
This hasn't been fixed... I know others who are having the same issue when they have this mod installed.
