### ISSUE TITLE
No CDI Glideslope Needle Deviation after Glideslope Capture

### ISSUE THREAD

**Issue by clarkpj1** [pimarc/pms50-gns530#29]
Latest MSFS and latest GNS530 mod, C172.  CDI Localizer needle deviates normally but have never seen CDI Glideslope needle move at all after autopilot goes from Glideslope Arm to Glideslope mode even when capture occurs below or above nominal Glideslope?  Is this normal?

**Comment by pimarc** [comment]
If this is an ILS approach and you have all the conditions to capture the glidescope (VLOC mode on GPS, autopilot in approach mode, correct frequency, correct altitude and position as published in your charts) then it will be displayed.
For a RNAV approach, I'm not sure the if the CDI is supposed to display a glidescope since there is no real signal.
Now all this stuff is not related to the GPS itself. This is your aircraft behavior.
