### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by GGIRT** [pimarc/pms50-gns530#3]
When using the small selection knob on the main map screen, scrolling right it crashes every time it hits a certain page. Hard to tell which one, I think it's the third one across.

**Comment by pimarc** [comment]
This is a bug in the sim's kernel. There is a CTD when using more than 4 maps for the same aircraft.
This could be the case with dual GPS as in the Cessna 172.
As a workaround, and before this bug being fixed by Asobo, I disabled all GNS430 maps if there is also a GNS530 in the aircraft.
Available from v 1.0.16.
