### ISSUE TITLE
gns430 issues

### ISSUE THREAD

**Issue by truespirt14** [pimarc/pms50-gns530#47]
On aircraft with only a GNS 430 present, like the Diamond Aircraft DA40 TDI, selecting an angle for OBS doesn't work, nor is there any indication of DME when tuned into a VOR or localizer.

**Comment by pimarc** [comment]
There is no OBS angle setting on the 430 here. The OBS angle should normally be set by the mechanical OBS on the HSI. The aircraft provider should provide it.
No DME on the 430.

**Comment by truespirt14** [comment]
There's a button for OBS on the 430 which even brings up the line.  It works perfectly and very functional except for the right knob not being able to rotate it like on the 530.  Wouldn't it be very simple to enable the knob to move it?  It moves if there is a 530 paired with it and that knob is used.
-------- Original message --------From: pimarc ***@***.***> Date: 6/22/21  9:24 AM  (GMT-05:00) To: pimarc/pms50-gns530 ***@***.***> Cc: truespirt14 ***@***.***>, Author ***@***.***> Subject: Re: [pimarc/pms50-gns530] gns430 issues (#47) 
There is no OBS angle setting on the 430 here. The OBS angle should normally be set by the mechanical OBS on the HSI. The aircraft provider should provide it.
No DME on the 430.

**Comment by pimarc** [comment]
Not so simple.
The OBS angle setting is not a standard feature and normally the mechanical OBS button should do the job (CDI or HSI). But Asobo didn't put the necessary code here. That's why we added the possibility to set the angle from the GNS530 main map after pushing the right knob.
Unfortunately, there is no such map in the 430. The only map is the second nav page and the right knob push is already used for the map pan mode.
