### ISSUE TITLE
OBS functionality in the GNS430

### ISSUE THREAD

**Issue by lerche89** [pimarc/pms50-gns530#48]
Hello
Thank you very much for a great mod. Is it possible to add OBS functionality to the GNS430. Just like you are able to change the OBS angle on the main nav page on the 530, it would be very nice to also have that option on the 430. The 430 is the only GPS usable in the new DC-6 from PMDG.
Thank you very much

**Comment by pimarc** [comment]
Not so simple.
The OBS angle setting is not a standard feature and normally the mechanical OBS button should do the job (CDI or HSI). But Asobo didn't put the necessary code here. That's why we added the possibility to set the angle from the GNS530 main map after pushing the right knob.
Unfortunately, there is no such map in the 430. The only map is the second nav page and the right knob push is already used for the map pan mode.
The best should be that PDMG adds the code to a mechanical OBS in HSI or CDI.
This code is very simple.
