### ISSUE TITLE
Nearest Airspace feature do not work after SU5

### ISSUE THREAD

**Issue by OleiDole89** [pimarc/pms50-gns530#55]
This feature worked perfectly before SU5. Now it do not show any airspaces.

**Comment by pimarc** [comment]
Yes, Asobo broke this code in SU5.
I have reported the bug while in SU5 beta but this has not been fixed yet.
We have a workaround (older Asobo code) and we'll use it if the bug is still not fixed in SU6.
Until that, we stay in this situation since this is not a major issue and I'd like to avoid too many workarounds to Asobo bugs. The list is already long enough!

**Comment by OleiDole89** [comment]
Aha, thank you for an informative answer and a great mod!:)

ons. 18. aug. 2021, 08:09 skrev pimarc ***@***.***>:

**Comment by pimarc** [comment]
A workaround has been set in latest release

**Comment by pimarc** [comment]
No sorry bad case for the last reply. No workaround for now.
