### ISSUE TITLE
Full range roll and bank 

### ISSUE THREAD

**Issue by Cele91** [pimarc/pms50-gns530#65]
With the plane leveled, in cruise, with HDG and ALT engaged, the plane begins to roll to one side or another in an extreme way ending up in a spin.

Same issue with Asobo C172 Classic and JustFlight P28R Arrow III .

**Comment by pimarc** [comment]
Hi,
This can't be a GPS issue because first, it doesn't control the autopilot, and second, you are in HDG mode so the autopilot doesn't follow the GPS. In HDG mode there is absolutely no relation between the GPS and the autopilot (only in NAV mode where the autopilot follows the GPS next waypoint).
So I close the case.
